#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 03, 2020 10:14:57 AM CST  platform: Windows NT

import sys
import pymysql
try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def addgrade():
    sno = w.Entry1_6.get()
    cno = w.Entry1_3.get()
    grade = w.Entry1_4.get()
    if sno == "" or cno == "":
        v.showerror("错误","课程和课程名不能为空")
    else:
        conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
        cur = conn.cursor()
        cur.execute("SELECT * FROM class WHERE cno = %s",cno)
        r2 = cur.fetchone()
        cur.execute("SELECT * FROM student WHERE sno = %s", sno)
        r1 = cur.fetchone()
        if r1 == None and r2 == None:
            v.showerror('error','学生信息和课程信息不存在，不能添加')
        elif r1 != None and r2 == None:
            v.showerror('error',cno+'课程信息不存在，不能添加')
        elif r2 != None and r1 == None:
            v.showerror('error', sno + '学生信息不存在，不能添加')
        else:
            values = ['',sno,cno,grade]
            cur.execute('INSERT INTO grade VALUES(%s,%s,%s,%s)',values)
            conn.commit()
            v.showinfo(cno, "添加成功")
    cur.close()
    conn.close()
    sys.stdout.flush()
    sys.stdout.flush()

def comeback():
    destroy_window()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import addgrade
    addgrade.vp_start_gui()




