#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 11:32:47 PM CST  platform: Windows NT

import sys
import pymysql
import xlrd
from tkinter import filedialog as a

try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def daoru():
    f = a.askopenfilename(filetypes = [("XLSX",".xlsx")])
    book = xlrd.open_workbook(f)
    w.Entry_url.insert(0,f)
    sheet = book.sheet_by_name("Sheet1")
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    query = 'insert into student(cno,cname,credit) values(%s,%s,%s)'

    for r in range(1,sheet.nrows):
        cno = sheet.cell(r,0).value
        cname = sheet.cell(r,1).value
        credit = sheet.cell(r, 2).value
        cur.execute('select sno from class where sno = %s',sno)
        r = cur.fetchone()
        if r == None:
            values = (cno,cname,credit)
            cur.execute(query, values)
        else:
            v.showerror('error',cno+'已经存在，请检查文件重新导入')
        conn.commit()
    cur.close()
    conn.close()
    columns = str(sheet.ncols)
    rows = str(sheet.nrows)
    print("导入 " +columns + " 列 " + rows + " 行数据到MySQL数据库!")
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import daoruclass
    daoruclass.vp_start_gui()




