#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 01, 2020 02:32:40 PM CST  platform: Windows NT

import sys
import pymysql

try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def comeback():
    destroy_window()
    sys.stdout.flush()

def delete():
    username = w.Entry1.get()
    try:
        conn = pymysql.connect(host = 'localhost', user = 'root', passwd = '809144', db = 'mydb',port = 3306)
        cur = conn.cursor()
        cur.execute('SELECT username FROM user WHERE username = %s',username)
        r = cur.fetchone()
        if r == None:
            v.showerror("error","不存在该用户名")
        else:
            cur.execute('DELETE FROM user WHERE username = %s',username)
            conn.commit()
            v.showinfo('suessful',username+'删除成功')
        cur.close()
        conn.close()
    except pymysql.Error as e:
        print('mysql error %d : %s' % (e.args[0],e.args[1]))
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import deleteuser
    deleteuser.vp_start_gui()




