#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 31, 2019 03:52:06 PM CST  platform: Windows NT

import sys
import pymysql
f1 = 0
try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()

def manager_login():
    global f1
    f1 = 1
    sys.stdout.flush()

def teacher_login():
    global f1
    f1 = 0
    sys.stdout.flush()

def login():
    global f1
    username = w.Entry_username.get()
    userpwd = w.Entry_password.get()
    try:
        conn = pymysql.connect(host = 'localhost', user = 'root', passwd = '809144', db = 'mydb',port = 3306)
        cur = conn.cursor()
        if f1 == 1:
            if username != "" and userpwd != "":
                cur.execute('SELECT password FROM user WHERE username = %s and qx = 1',username)
                r = cur.fetchone()
                if r == None:
                    v.showerror(username,"不存在此用户")
                elif r[0]== userpwd:
                    v.showinfo(username,"登录成功")
                    destroy_window()
                    import manager
                    manager.vp_start_gui()
                else:
                    v.showerror(username,"登录失败，请检查用户名和密码")
            else:
                v.showerror(username, "用户名和密码不能为空")
        elif f1 == 0:
            if username != "" and userpwd != "":
                cur.execute('SELECT password FROM user WHERE username = %s and qx = 0',username)
                r = cur.fetchone()
                print(r)
                if r == None:
                    v.showerror(username, "不存在此用户")
                elif r[0] == userpwd:
                    v.showinfo(username, "登录成功")
                    destroy_window()
                    import teacher
                    teacher.vp_start_gui()
                else:
                    v.showerror(username, "登录失败，请检查用户名和密码")
            else:
                v.showerror(username, "用户名和密码不能为空")
        cur.close()
        conn.close()
    except pymysql.Error as e:
        print('mysql error %d : %s' % (e.args[0],e.args[1]))
    sys.stdout.flush()

def quit():
    root.quit()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import login
    login.vp_start_gui()




