#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 08:51:20 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox1
    combobox1 = tk.StringVar()
    global combobox2
    combobox2 = tk.StringVar()
    global combobox3
    combobox3 = tk.StringVar()
    global combobox4
    combobox4 = tk.StringVar()

def logout():
    destroy_window()
    import login
    login.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import manager
    manager.vp_start_gui()




