#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 11:46:07 PM CST  platform: Windows NT

import sys
import pymysql
import updateclass
global f
f = 0
try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def adds():
    import addclass
    addclass.vp_start_gui()
    sys.stdout.flush()

def allfind():
    global f
    f = 0
    delButton()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    cur.execute('select * from class')
    r = cur.fetchall()
    i = 0
    for r1 in r:
        w.Scrolledtreeview1.insert('', i, values=(r1[0], r1[1], r1[2]))
        i += 1
    sys.stdout.flush()

def p(event):#bind函数
    cur = w.Scrolledtreeview1.focus()
    return w.Scrolledtreeview1.item(cur)

def cnofind():
    global f
    f = 2
    delButton()
    cno = w.cno.get()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    cur.execute('select * from class where cno = %s', cno)
    r = cur.fetchall()
    i = 0
    if r != ():
        for r1 in r:
            w.Scrolledtreeview1.insert('', i, values=(r1[0], r1[1], r1[2]))
            i += 1
    else:
        v.showerror('error', cno + '不存在，请检查后重新输入')
    sys.stdout.flush()

def delButton():
    x=w.Scrolledtreeview1.get_children()
    for item in x:
        w.Scrolledtreeview1.delete(item)

def deletes():
    global f
    c = p('')
    w.Scrolledtreeview1.bind('<ButtonRelease-1>',p)
    if c.get('values') != '':
        cno = c.get('values')[0]
        conn = pymysql.connect(host = 'localhost', user = 'root', passwd = '809144', db = 'mydb',port = 3306)
        cur = conn.cursor()
        cur.execute('DELETE FROM class WHERE cno = %s', cno)
        conn.commit()
        v.showinfo('suessful','删除成功')
    if f == 0:
        allfind()
    elif f == 2:
        cnofind()
    elif f == 1:
        namefind()
    sys.stdout.flush()

def namefind():
    global f
    f = 1
    delButton()
    cname = w.cname.get()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    cur.execute('select * from class where cname = %s',cname)
    r = cur.fetchall()
    i = 0
    if r != ():
        for r1 in r:
            w.Scrolledtreeview1.insert('', i, values=(r1[0], r1[1], r1[2]))
            i += 1
    else:
        v.showerror('error',cname+"信息不存在，请检查后重新输入")

    sys.stdout.flush()

def updates():
    c = p('')
    w.Scrolledtreeview1.bind('<ButtonRelease-1>',p)
    if c.get('values') != '':
        cno = c.get('values')[0]
        cname = c.get('values')[1]
        credit = c.get('values')[2]
        updateclass.vp_start_gui(cno,cname,credit)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import querycno
    querycno.vp_start_gui()




