#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 11:46:03 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import querycno_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    querycno_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    querycno_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1023x591+524+129")
        top.minsize(152, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("学生信息查询")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.style.configure('Treeview',  font="TkDefaultFont")
        self.Scrolledtreeview1 = ScrolledTreeView(top,show = 'headings')
        self.Scrolledtreeview1.place(relx=0.098, rely=0.389, relheight=0.469
                , relwidth=0.425)
        self.Scrolledtreeview1.configure(columns="Col1 Col2 Col3")
        # build_treeview_support starting.
        self.Scrolledtreeview1.heading("#0",text="Tree")
        self.Scrolledtreeview1.heading("#0",anchor="center")
        self.Scrolledtreeview1.column("#0",width="55")
        self.Scrolledtreeview1.column("#0",minwidth="20")
        self.Scrolledtreeview1.column("#0",stretch="1")
        self.Scrolledtreeview1.column("#0",anchor="center")
        self.Scrolledtreeview1.heading("Col1",text="课程号")
        self.Scrolledtreeview1.heading("Col1",anchor="center")
        self.Scrolledtreeview1.column("Col1",width="119")
        self.Scrolledtreeview1.column("Col1",minwidth="20")
        self.Scrolledtreeview1.column("Col1",stretch="1")
        self.Scrolledtreeview1.column("Col1",anchor="center")
        self.Scrolledtreeview1.heading("Col2",text="课程名")
        self.Scrolledtreeview1.heading("Col2",anchor="center")
        self.Scrolledtreeview1.column("Col2",width="120")
        self.Scrolledtreeview1.column("Col2",minwidth="20")
        self.Scrolledtreeview1.column("Col2",stretch="1")
        self.Scrolledtreeview1.column("Col2",anchor="center")
        self.Scrolledtreeview1.heading("Col3",text="学分")
        self.Scrolledtreeview1.heading("Col3",anchor="center")
        self.Scrolledtreeview1.column("Col3",width="118")
        self.Scrolledtreeview1.column("Col3",minwidth="20")
        self.Scrolledtreeview1.column("Col3",stretch="1")
        self.Scrolledtreeview1.column("Col3",anchor="center")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.09, rely=0.102, height=32, width=156)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="#000000")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {等线} -size 15")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''课程名查询：''')

        self.cname = tk.Entry(top)
        self.cname.place(relx=0.244, rely=0.102,height=31, relwidth=0.18)
        self.cname.configure(background="white")
        self.cname.configure(disabledforeground="#a3a3a3")
        self.cname.configure(font="TkFixedFont")
        self.cname.configure(foreground="#000000")
        self.cname.configure(highlightbackground="#d9d9d9")
        self.cname.configure(highlightcolor="black")
        self.cname.configure(insertbackground="black")
        self.cname.configure(selectbackground="#c4c4c4")
        self.cname.configure(selectforeground="black")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.089, rely=0.203, height=32, width=156)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {等线} -size 15")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''课程号查询：''')

        self.cno = tk.Entry(top)
        self.cno.place(relx=0.244, rely=0.203,height=31, relwidth=0.18)
        self.cno.configure(background="white")
        self.cno.configure(disabledforeground="#a3a3a3")
        self.cno.configure(font="TkFixedFont")
        self.cno.configure(foreground="#000000")
        self.cno.configure(highlightbackground="#d9d9d9")
        self.cno.configure(highlightcolor="black")
        self.cno.configure(insertbackground="black")
        self.cno.configure(selectbackground="#c4c4c4")
        self.cno.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.459, rely=0.102, height=32, width=62)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=querycno_support.namefind)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {等线} -size 13")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''查询''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.459, rely=0.203, height=37, width=61)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=querycno_support.cnofind)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {等线} -size 13")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''查询''')

        self.Label2_12 = tk.Label(top)
        self.Label2_12.place(relx=0.117, rely=0.288, height=32, width=131)
        self.Label2_12.configure(activebackground="#f9f9f9")
        self.Label2_12.configure(activeforeground="black")
        self.Label2_12.configure(background="#d9d9d9")
        self.Label2_12.configure(disabledforeground="#a3a3a3")
        self.Label2_12.configure(font="-family {等线} -size 15")
        self.Label2_12.configure(foreground="#000000")
        self.Label2_12.configure(highlightbackground="#d9d9d9")
        self.Label2_12.configure(highlightcolor="black")
        self.Label2_12.configure(text='''全部查询：''')

        self.Button2_13 = tk.Button(top)
        self.Button2_13.place(relx=0.254, rely=0.288, height=37, width=171)
        self.Button2_13.configure(activebackground="#ececec")
        self.Button2_13.configure(activeforeground="#000000")
        self.Button2_13.configure(background="#d9d9d9")
        self.Button2_13.configure(command=querycno_support.allfind)
        self.Button2_13.configure(disabledforeground="#a3a3a3")
        self.Button2_13.configure(font="-family {等线} -size 13")
        self.Button2_13.configure(foreground="#000000")
        self.Button2_13.configure(highlightbackground="#d9d9d9")
        self.Button2_13.configure(highlightcolor="black")
        self.Button2_13.configure(pady="0")
        self.Button2_13.configure(text='''查询''')

        self.Button2_14 = tk.Button(top)
        self.Button2_14.place(relx=0.587, rely=0.745, height=37, width=281)
        self.Button2_14.configure(activebackground="#ececec")
        self.Button2_14.configure(activeforeground="#000000")
        self.Button2_14.configure(background="#d9d9d9")
        self.Button2_14.configure(command=querycno_support.deletes)
        self.Button2_14.configure(disabledforeground="#a3a3a3")
        self.Button2_14.configure(font="-family {等线} -size 13")
        self.Button2_14.configure(foreground="#000000")
        self.Button2_14.configure(highlightbackground="#d9d9d9")
        self.Button2_14.configure(highlightcolor="black")
        self.Button2_14.configure(pady="0")
        self.Button2_14.configure(text='''删除''')

        self.Button2_15 = tk.Button(top)
        self.Button2_15.place(relx=0.587, rely=0.389, height=37, width=281)
        self.Button2_15.configure(activebackground="#ececec")
        self.Button2_15.configure(activeforeground="#000000")
        self.Button2_15.configure(background="#d9d9d9")
        self.Button2_15.configure(command=querycno_support.updates)
        self.Button2_15.configure(disabledforeground="#a3a3a3")
        self.Button2_15.configure(font="-family {等线} -size 13")
        self.Button2_15.configure(foreground="#000000")
        self.Button2_15.configure(highlightbackground="#d9d9d9")
        self.Button2_15.configure(highlightcolor="black")
        self.Button2_15.configure(pady="0")
        self.Button2_15.configure(text='''修改''')

        self.Button2_16 = tk.Button(top)
        self.Button2_16.place(relx=0.587, rely=0.558, height=37, width=281)
        self.Button2_16.configure(activebackground="#ececec")
        self.Button2_16.configure(activeforeground="#000000")
        self.Button2_16.configure(background="#d9d9d9")
        self.Button2_16.configure(command=querycno_support.adds)
        self.Button2_16.configure(disabledforeground="#a3a3a3")
        self.Button2_16.configure(font="-family {等线} -size 13")
        self.Button2_16.configure(foreground="#000000")
        self.Button2_16.configure(highlightbackground="#d9d9d9")
        self.Button2_16.configure(highlightcolor="black")
        self.Button2_16.configure(pady="0")
        self.Button2_16.configure(text='''添加''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="-family {Microsoft YaHei UI} -size 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





