#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 10:28:29 PM CST  platform: Windows NT

import sys
import pymysql
import updatestudent
global f
f = 0
try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def adds():
    import addstudent
    addstudent.vp_start_gui()
    sys.stdout.flush()

def allfind():
    global f
    f = 0
    delButton()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    cur.execute('select * from student')
    r = cur.fetchall()
    i = 0
    for r1 in r:
        w.Scrolledtreeview1.insert('', i, values=(r1[0], r1[1], r1[2],r1[3],r1[4],r1[5]))
        i += 1
    sys.stdout.flush()

def p(event):#bind函数
    cur = w.Scrolledtreeview1.focus()
    return w.Scrolledtreeview1.item(cur)

def deletes():
    global f
    c = p('')
    w.Scrolledtreeview1.bind('<ButtonRelease-1>',p)
    if c.get('values') != '':
        sno = c.get('values')[0]
        conn = pymysql.connect(host = 'localhost', user = 'root', passwd = '809144', db = 'mydb',port = 3306)
        cur = conn.cursor()
        cur.execute('DELETE FROM student WHERE sno = %s', sno)
        conn.commit()
        v.showinfo('suessful','删除成功')
    if f == 0:
        allfind()
    elif f == 2:
        snofind()
    elif f == 1:
        namefind()
    sys.stdout.flush()


def namefind():
    global f
    f = 1
    delButton()
    sname = w.fname.get()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    cur.execute('select * from student where sname = %s',sname)
    r = cur.fetchall()
    i = 0
    if r != ():
        for r1 in r:
            w.Scrolledtreeview1.insert('', i, values=(r1[0], r1[1], r1[2],r1[3],r1[4],r1[5]))
            i += 1
    else:
        v.showerror('error',sname+"信息不存在，请检查后重新输入")
    sys.stdout.flush()

def snofind():
    global f
    f = 2
    delButton()
    sno = w.fsno.get()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    cur.execute('select * from student where sno = %s', sno)
    r = cur.fetchall()
    i = 0
    if r != ():
        for r1 in r:
            w.Scrolledtreeview1.insert('', i, values=(r1[0], r1[1], r1[2], r1[3], r1[4], r1[5]))
            i += 1
    else:
        v.showerror('error', sno + '不存在，请检查后重新输入')
    sys.stdout.flush()

def delButton():
    x=w.Scrolledtreeview1.get_children()
    for item in x:
        w.Scrolledtreeview1.delete(item)

def updates():
    c = p('')
    w.Scrolledtreeview1.bind('<ButtonRelease-1>',p)
    if c.get('values') != '':
        sno = c.get('values')[0]
        sname = c.get('values')[1]
        sex= c.get('values')[2]
        sage = c.get('values')[3]
        dept = c.get('values')[4]
        class1 = c.get('values')[5]
        updatestudent.vp_start_gui(sno,sname,sex,sage,dept,class1)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import querystudent
    querystudent.vp_start_gui()




