#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 03, 2020 11:53:43 AM CST  platform: Windows NT

import sys
import pymysql
try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def comeback():
    destroy_window()
    sys.stdout.flush()

def updates():
    sno = w.Entry1.get()
    cno = w.Entry2.get()
    grade = w.Entry4.get()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    values = [grade,sno,cno]
    cur.execute('select * from student where sno = %s',sno)
    r = cur.fetchone()
    if r != None:
        cur.execute('update grade set grade = %s where sno = %s and cno = %s',values)
        v.showinfo('successful',sno+'成绩信息更新成功')
        conn.commit()
        cur.close()
        conn.close()
        destroy_window()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import updategrade
    updategrade.vp_start_gui()




