#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 11:54:20 PM CST  platform: Windows NT

import sys
import pymysql

try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def comeback():
    destroy_window()
    sys.stdout.flush()

def updates():
    cno = w.Entry1.get()
    cname = w.Entry2.get()
    credit = w.Entry4.get()
    conn = pymysql.connect(host='localhost', user='root', passwd='809144', db='mydb', port=3306)
    cur = conn.cursor()
    values = [cname,credit,cno]
    cur.execute('select * from class where cno = %s',cno)
    r = cur.fetchone()
    if r != None:
        cur.execute('update class set cname = %s,credit = %s where cno = %s',values)
        v.showinfo('successful',cname+'信息更新成功')
        conn.commit()
        cur.close()
        conn.close()
        destroy_window()
    else:
        v.showerror('error',cname+'信息不存在，请确认')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import updateclass
    updateclass.vp_start_gui()




