#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 01, 2020 01:45:22 PM CST  platform: Windows NT

import sys
import pymysql
try:
    import Tkinter as tk
    import Tkinter.messagebox as v
except ImportError:
    import tkinter as tk
    import tkinter.messagebox as v

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def comeback():
    destroy_window()
    sys.stdout.flush()

def update():
    username = w.Entryusername.get()
    password = w.Entrypwd.get()
    password1 = w.Entrypwd1.get()
    qx1 = w.Entryqx.get()
    try:
        conn = pymysql.connect(host = 'localhost', user = 'root', passwd = '809144', db = 'mydb',port = 3306)
        cur = conn.cursor()
        cur.execute('select password from user where username = %s',username)
        r = cur.fetchone()
        if r != None:
            if r[0] != password:
                v.showerror('error','旧密码输入错误')
            else:
                values = [password1,qx1,username]
                cur.execute('update user set password = %s,qx = %s where username = %s',values)
                conn.commit()
                v.showinfo('successful',username+'信息已更新')
                cur.close()
        else:
            v.showerror('error','不存在此用户')
            conn.close()
    except pymysql.Error as e:
        print('mysql error %d : %s' % (e.args[0],e.args[1]))
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import updateuser
    updateuser.vp_start_gui()




